# Generated by https://quicktype.io

from typing import Optional, List
from datetime import datetime


class Athlete:
    id: int
    resource_state: int

    def __init__(self, id: int, resource_state: int) -> None:
        self.id = id
        self.resource_state = resource_state


class Map:
    id: str
    summary_polyline: Optional[str]
    resource_state: int

    def __init__(self, id: str, summary_polyline: Optional[str], resource_state: int) -> None:
        self.id = id
        self.summary_polyline = summary_polyline
        self.resource_state = resource_state


class ActivitiesResponseElement:
    resource_state: int
    athlete: Athlete
    name: str
    distance: float
    moving_time: int
    elapsed_time: int
    total_elevation_gain: float
    type: str
    workout_type: Optional[int]
    id: int
    external_id: str
    upload_id: int
    start_date: datetime
    start_date_local: datetime
    timezone: str
    utc_offset: float
    start_latlng: List[float]
    end_latlng: List[float]
    location_city: None
    location_state: None
    location_country: None
    start_latitude: Optional[float]
    start_longitude: Optional[float]
    achievement_count: int
    kudos_count: int
    comment_count: int
    athlete_count: int
    photo_count: int
    map: Map
    trainer: bool
    commute: bool
    manual: bool
    private: bool
    visibility: str
    flagged: bool
    gear_id: None
    from_accepted_tag: bool
    upload_id_str: str
    average_speed: float
    max_speed: float
    has_heartrate: bool
    heartrate_opt_out: bool
    display_hide_heartrate_option: bool
    elev_high: Optional[float]
    elev_low: Optional[float]
    pr_count: int
    total_photo_count: int
    has_kudoed: bool

    def __init__(self, resource_state: int, athlete: Athlete, name: str, distance: float, moving_time: int, elapsed_time: int, total_elevation_gain: float, type: str, workout_type: Optional[int], id: int, external_id: str, upload_id: int, start_date: datetime, start_date_local: datetime, timezone: str, utc_offset: float, start_latlng: List[float], end_latlng: List[float], location_city: None, location_state: None, location_country: None, start_latitude: Optional[float], start_longitude: Optional[float], achievement_count: int, kudos_count: int, comment_count: int, athlete_count: int, photo_count: int, map: Map, trainer: bool, commute: bool, manual: bool, private: bool, visibility: str, flagged: bool, gear_id: None, from_accepted_tag: bool, upload_id_str: str, average_speed: float, max_speed: float, has_heartrate: bool, heartrate_opt_out: bool, display_hide_heartrate_option: bool, elev_high: Optional[float], elev_low: Optional[float], pr_count: int, total_photo_count: int, has_kudoed: bool) -> None:
        self.resource_state = resource_state
        self.athlete = athlete
        self.name = name
        self.distance = distance
        self.moving_time = moving_time
        self.elapsed_time = elapsed_time
        self.total_elevation_gain = total_elevation_gain
        self.type = type
        self.workout_type = workout_type
        self.id = id
        self.external_id = external_id
        self.upload_id = upload_id
        self.start_date = start_date
        self.start_date_local = start_date_local
        self.timezone = timezone
        self.utc_offset = utc_offset
        self.start_latlng = start_latlng
        self.end_latlng = end_latlng
        self.location_city = location_city
        self.location_state = location_state
        self.location_country = location_country
        self.start_latitude = start_latitude
        self.start_longitude = start_longitude
        self.achievement_count = achievement_count
        self.kudos_count = kudos_count
        self.comment_count = comment_count
        self.athlete_count = athlete_count
        self.photo_count = photo_count
        self.map = map
        self.trainer = trainer
        self.commute = commute
        self.manual = manual
        self.private = private
        self.visibility = visibility
        self.flagged = flagged
        self.gear_id = gear_id
        self.from_accepted_tag = from_accepted_tag
        self.upload_id_str = upload_id_str
        self.average_speed = average_speed
        self.max_speed = max_speed
        self.has_heartrate = has_heartrate
        self.heartrate_opt_out = heartrate_opt_out
        self.display_hide_heartrate_option = display_hide_heartrate_option
        self.elev_high = elev_high
        self.elev_low = elev_low
        self.pr_count = pr_count
        self.total_photo_count = total_photo_count
        self.has_kudoed = has_kudoed
